### ISSUE TITLE
Some lingering bugs

### ISSUE THREAD

**Issue by Vectorial1024** [emipa606/Tenants#3]
I found some (lingering?) bugs when trying to verify the earlier bug fix about silver not saving correctly; it seems like it is a revert of what was seemingly fixed:

- For mailboxes that are supposedly empty before the update, and when a courier is arriving to deliver silver:
  - Couriers could not deliver silver again: NullPointer when trying to store silver
  - Try to tell colonist to prioritize deconstructing the mailbox for testing, but cannot: NullPointer when right-clicking on mailbox

Using inspector -> deep inspection mode:

- Mailbox: Items list is null; perhaps they are not properly initialized on the aspect of self-patching

It would seem that this repo is now using features from C# 10, and that my VS version is severely outdated, so I cannot react to this for now, but just gonna write this down for future follow-up.

**Comment by emipa606** [comment]
I based the fix on your earlier pr and just changed the silver scribe to deep instead of reference. 
Ill add an extra initializer of the list in your modified code and hopefully that will fix it

**Comment by emipa606** [comment]
Hopefully fixed in 0cc91dd

**Comment by Vectorial1024** [comment]
Yes it works now, thanks again!
